spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://47.114.37.29:3306/weibiansanjue?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    url: jdbc:mysql://127.0.0.1:3306/weibiansanjue?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  resources:
    static-locations: classpath:templates/,classpath:static/,file:E:/weibiansanjue

  redis:
    host: 127.0.0.1
    port: 6379
    password:


#    settings:
#      classic_compatible: true


mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml